"""开箱即用的默认世界配置。

设计目标：零依赖、零配置、装上就跑，同时体现「她住在群里」的生活感。

关于动作的分工（v1.7 调整）：
- **互动类动作**（抱抱/亲亲/摸头/微笑/挥手/倒茶）一律用模板层级 + ``{bot}``/``{user}`` 占位符，
  零 token、文案稳定，并且都带数值联动（孤独下降、心潮上升——抱抱亲亲比挥手更能搅动心绪）；
- **体验类动作**（发呆/看书/做饭）时长交给大模型决定，效果按"每持续 1 分钟"累加，
  做完还能让大模型把经历讲成人话（``llm_followup``）；
- 默认不启用任何工具（``global_allowed_tools`` 为空、动作绑定的工具可能并不存在），
  因此没装搜索/天气工具时相关动作会被自动跳过，不会报错。
"""

from __future__ import annotations

import copy
from typing import Any

# 「明确叫醒她」的说法：命中这些词（且消息是 @ 她的）才打断睡眠，否则只回睡觉时的固定文案
DEFAULT_WAKE_WORDS = ("醒醒", "起床", "别睡", "醒来", "起来啦", "别睡了")

# 图片转述模型的默认提示词（在「全局设置 → 图片转述」里可以改）。
# 除了画面本身，还要认出「这是不是表情包」——接梗图接错比接不上更尴尬。
# 「看图」提示词：只描述图片本身，**不写**与话题的关系——
# 关系由下面那段纯文本提示词单独生成，这样这段结果可以跨话题复用（缓存）。
DEFAULT_CAPTION_PROMPT = (
    "你是群聊图片转述器，只把图片转成一行中文，供没有多模态能力的主模型接话。"
    "只输出一行，不换行、不分点、不客套、不写「这张图片」、不编造看不到的内容。\n"
    "格式固定：画面描述｜类型｜文字\n"
    "画面描述：**只写你在图里真的看到的东西**（主体、动作、表情），40 字以内；"
    "看不出在做什么就写「看不出来」，不要根据别处的话题去猜画面。\n"
    "类型：表情包 / 梗图、截图、照片、其它。"
    "有卡通角色、玩梗、拼接、配字的图算**表情包 / 梗图**；"
    "只有聊天界面、网页、对话框排版那种才是「截图」；拿不准写「其它」。"
    "梗图写清能认出的梗和情绪；认不出写「疑似梗图，情绪X，具体梗不明」。\n"
    "文字：**只照抄图上看得见的字**（关键句优先；字多时给图上文字本身的主旨），60~80 字；"
    "看不清写「文字模糊/部分可辨」；没有文字写「无」。"
    "**别在「文字」里写画面描述、场景想象或你的推断**。"
    "文字里禁止出现「｜」和换行，用逗号或空格代替。\n"
    "不要写这张图和话题的关系——那部分由另一段提示词单独生成。"
)

# 「关系」提示词：输入是上一步的文字转述 + 当前消息 + 最近群聊，**不带图**。
DEFAULT_CAPTION_RELATION_PROMPT = (
    "你会拿到图片的文字转述，以及机器人收到的那条消息和最近群聊。"
    "你不需要看图，只判断这张图和正在聊的事有什么关系。\n"
    "**只有一张图**：只输出一行，格式固定：与话题的关系：…（不要写「图1：」）。\n"
    "**多张图**：每张各一行，**只**以「图1：」「图2：」开头，"
    "后面直接写关系本身——**不要再写一次「与话题的关系」这几个字**。\n"
    "说清这张图在回应什么、和大家聊的事有什么关联；看不出直接关系就写「看不出直接关系」。"
    "不要复述画面描述、不要客套、不要分点。"
)

# 天气归一化提示词：输入可能是天气工具返回的一段文字，也可能是天气图的转述结果。
DEFAULT_WEATHER_PROMPT = (
    "你是天气信息整理器。把给你的天气内容压成一行中文，供另一个模型直接引用。\n"
    "只输出一行，不要解释、不要客套、不要分点、不要换行。\n"
    "格式固定：城市｜温度｜天气｜湿度｜风力｜一句话预报\n"
    "温度写成「26℃」，天气写「多云转小雨」，湿度写「68%」，风力写「东南风3级」，"
    "预报一句话说清接下来是转晴还是转雨、要不要带伞。\n"
    "内容里没提到的字段留空，不要编；实在读不出天气就只输出「读不出天气」。"
)

# 合并转发摘要提示词：把一长串转发聊天记录（可能带图）压成一段摘要，
# 直接替换进她的聊天记录里——转发的原文往往是几十条消息，原样带进上下文会挤掉别的。
DEFAULT_FORWARD_PROMPT = (
    "你在读一段被转发的聊天记录（可能有多个人在说话，可能带图）。"
    "把它压成一段中文摘要，供另一个模型当聊天背景使用。\n"
    "只输出摘要本身：不要标题、不要分点、不要「这段记录」之类的开场、不要复述每一句。\n"
    "要写清：谁和谁在聊、事情是什么、结论或分歧在哪、有没有提到具体的时间 / 数字 / 约定；"
    "图里的内容（画面、图上的字）如果和话题有关就写进去，用「图1」指代。\n"
    "用一句话到几句话讲明白，不分段、不换行；读不出重点就直接说这段记录没什么实质内容。"
)

DEFAULT_WORLD: dict[str, Any] = {
    "world_id": "default",
    "name": "小世界",
    "bot_name": "",
    "schema_version": 1,
    # 她是谁：插件自己的人设。默认沿用 AstrBot 里那个会话选的人格（老行为不变），
    # 填上以后就固定用这一份、跟着预设走，不再随会话组/会话变动漂移。
    "persona": {
        "mode": "astrbot",
        "text": "",
    },
    "global_prompt": (
        "这是一个群聊虚拟世界。你有一个私有空间和自己的生活节奏。"
        "你的行为应该自然地反映你的位置和状态，但不要向用户解释地图、规则或系统。"
    ),
    "timezone": "Asia/Shanghai",
    "default_state": {
        "mood": "平静",
        "energy": 0.6,
        "loneliness": 0.5,
        "curiosity": 0.5,
        "affect": 0.3,
        "boredom": 0.3,
    },
    "state_dynamics": {
        "energy_decay_per_min": 0.0015,
        "loneliness_growth_per_min": 0.0008,
        "curiosity_growth_per_min": 0.0010,
        "affect_decay_per_min": 0.02,
        "boredom_growth_per_min": 0.0012,
        "sleep_energy_recovery_per_min": 0.0020,
        "nap_energy_recovery_per_min": 0.0008,
        "sleep_curiosity_decay_per_min": 0.0012,
        "sleep_curiosity_floor": 0.30,
        "atmosphere_multiplier": 0.5,
        "mood_override_duration": 600,
    },
    # 「说话频率与预算」不在这儿写死：它跟着 core/models.py 的 Limits 走——
    # 两处各存一份的结果是"新建默认预设"会把旧的保守值又装回来（真的发生过）。
    "engagement": {
        "unanswered_threshold": 3,
        "silence_window_minutes": 60,
        "cooldown_after_unanswered": 120,
        "halve_on_cooldown_end": True,
        "after_reply_cooldown_minutes": 10,
    },
    "nickname_sync": {
        "enabled": True,
        "template": "{base} | {status}",
        "max_length": 30,
        "cooldown_seconds": 60,
        "restore_on_idle": True,
        "restore_on_idle_delay": 30,
        # 文案现在写在动作和地点自己身上（动作 → 执行中名片文案、地点 → 在这里时名片文案）。
        # 这两张表留作老配置的兜底：新装用户是空的，老配置里的映射会在解析时搬到动作 / 地点上。
        "status_map": {},
        "node_status": {},
    },
    "memory_scope_mode": "group_persona",
    "memory_scope_fallback": True,
    "memory_scope_warn_on_switch": True,
    "memory_conflict_policy": "newest",
    "global_allowed_tools": [],
    "tool_filter_enabled": True,
    # 睡觉时怎么回应、怎么把她叫起来
    "sleep": {
        "reply_mode": "template",
        "reply_text": "zzz…（{bot}睡觉中，要叫她起来吗？）",
        "reply_cooldown_minutes": 5,
        "wake_words": list(DEFAULT_WAKE_WORDS),
        "wake_requires_mention": True,
        "clear_plan_on_wake": True,
        "applies_to_nap": True,
        "wake_grace_minutes": 12,
        "block_plugins": True,
        "block_scope": "unmentioned",
        # 迷糊惊醒：没人明确叫她、但实在吵，她会半睡半醒回两句再接着睡
        "startled": {
            "enabled": True,
            "window_minutes": 5,
            "noise_threshold": 8,
            "noise_threshold_nap": 5,
            "named_threshold": 2,
            "skip_first_minutes": 30,
            "max_per_sleep": 1,
            "awake_minutes": 3,
            "energy_penalty": 0.05,
            "grumpy_minutes": 15,
            "grumpy_valence": -0.05,
            "grumpy_affect": 0.06,
        },
        # 起床气：睡整觉醒来的结算（睡饱 -> 清爽；没睡够 -> 有气）
        "quality": {
            "enabled": True,
            "full_minutes": 360,
            "grumpy_minutes": 30,
            "grumpy_valence": -0.12,
            "grumpy_affect": 0.10,
            "rested_valence": 0.08,
            "rested_affect": -0.05,
        },
    },
    # 群聊上下文：留档持久化，带进提示词的只是其中一小份
    # 同理：上下文的预算跟着 ContextConfig 走，不在这儿另存一份
    # 说话的节奏：分段之间的打字停顿，以及"话太密"的判定
    "reply_style": {
        "typing_delay_enabled": True,
        "typing_delay_per_char": 0.03,
        "typing_delay_max": 2.5,
        "dense_window_minutes": 10,
        "dense_max_lines": 4,
    },
    # 图片转述：交给多模态模型的那段提示词（留空则用内置默认）
    "vision": {
        "prompt": DEFAULT_CAPTION_PROMPT,
        "relation_prompt": DEFAULT_CAPTION_RELATION_PROMPT,
        # 看图（多模态、贵）只做一次并缓存；关系分析是纯文本、每次现算
        "relation_enabled": True,
        # 同一张图只识别一次：表情包/梗图会反复出现，按图片指纹缓存、重启后仍在
        "cache_enabled": True,
        "cache_max": 500,
        "cache_days": 30,
    },
    # 天气：全局共享一份，按需静默刷新，写进提示词也画在编辑器地图页顶部
    "weather": {
        "enabled": True,
        "city": "",
        # 每隔几小时静默查一次（她主动查过会顺延）
        "refresh_hours": 2,
        # 超过这么久就不再写进提示词（默认 1 天）
        "stale_hours": 24,
        # 结果先交给小模型压成「城市｜温度｜…」再存
        "normalize": True,
    },
    # 夜晚时段：睡觉动作只在夜里可选，夜里醒着也要付熬夜代价
    "night": {
        "start_hour": 23,
        "end_hour": 7,
        "sleep_only_at_night": True,
    },
    "content_safety": {
        "blocked_words": [],
        "message_blocklist": [],
        "session_blocklist": [],
    },
    # 用户画像 / 关系 / 好感度 / 回想回访（见 core/profile.py）
    "profile": {
        "enabled": True,
        "consolidate_enabled": True,
        "sleep_consolidate_minutes": 20,
        "sleep_consolidate_late_minutes": 300,
        "nap_consolidate": True,
        "affinity_initial": 0.0,
        "affinity_min": -100.0,
        "affinity_max": 100.0,
        # 好感的"日常"三条：混脸熟 / 每轮模型判断 / 慢慢回落（防着靠私聊刷满）
        "affinity_reply_max": 3.0,
        "affinity_daily_max": 10.0,
        "presence_affinity": 0.05,
        "presence_cooldown_minutes": 10,
        "presence_daily_max": 2.0,
        "affinity_decay_per_day": 0.2,
        "digest_chars": 60,
        "digest_limit": 5,
        "recall_daily_max": 5,
        "recall_per_user_daily_max": 2,
        "recall_topic_gap_days": 7,
        "miss_growth_per_min": 0.0006,
        "miss_cooldown_min_minutes": 45,
        "miss_cooldown_max_minutes": 240,
        "miss_loneliness_weight": 0.8,
        "miss_threshold": 0.6,
        "miss_limit": 3,
        # 软推：真想得不行了，就让她主动去找他一次（在哪说由她自己决定）
        "miss_push_enabled": True,
        "miss_push_threshold": 0.85,
        "miss_push_daily_max": 2,
        "call_name_blacklist": [],
        "bond_conflict_policy": "reject",
        "default_bond": "陌生人",
        # 关系类型 → 亲密度的下限 / 上限（都是 level 的下标）。
        # floor 是"关系本身带来的态度"：绑成男友之后，好感还没养起来也该能抱抱；
        # cap 是"上限"：普通关系聊再久也上不去，只有关系本身升级才会放宽。
        # 生效档位 = 好感给的档位，先被 floor 抬起、再被 cap 压下。
        "bonds": [
            {"name": "陌生人", "slot": "stranger", "floor": 2, "cap": 2,
             "aliases": ["不认识", "没见过"]},
            {"name": "群友", "slot": "acquaintance", "group": "close", "floor": 2, "cap": 3,
             "aliases": ["网友", "同群的"]},
            {"name": "朋友", "slot": "friend", "group": "close", "floor": 3, "cap": 4,
             "aliases": ["好朋友", "老铁"]},
            {"name": "闺蜜", "slot": "bestie", "group": "close", "floor": 4, "cap": 5, "unique": True,
             "aliases": ["死党", "挚友"]},
            {"name": "主人", "slot": "guardian", "floor": 4, "cap": 5, "unique": True,
             "aliases": ["主人さま", "老板"]},
            {"name": "男友", "slot": "romance", "group": "close", "floor": 5, "cap": 6, "unique": True,
             "aliases": ["男朋友", "老公", "恋人", "未婚夫"]},
            {"name": "女友", "slot": "romance", "group": "close", "floor": 5, "cap": 6, "unique": True,
             "aliases": ["女朋友", "老婆", "未婚妻"]},
            {"name": "家人", "slot": "family", "floor": 4, "cap": 6,
             "aliases": ["哥哥", "姐姐", "弟弟", "妹妹"]},
            {"name": "讨厌的人", "slot": "rival", "floor": 0, "cap": 1, "negative": True,
             "aliases": ["烦人精", "讨厌鬼"]},
            {"name": "敌人", "slot": "enemy", "floor": 0, "cap": 0, "negative": True,
             "aliases": ["仇人"]},
        ],
        # 亲密度分级：每一级自己的称呼、允许 / 禁止的动作、主动频率，以及给模型的提示词文本。
        "levels": [
            {
                "name": "敌意",
                "min_affinity": -100.0,
                "max_affinity": -40.0,
                "address": "你",
                "deny": ["hug", "kiss", "pat", "selfie", "leg_photo", "pour_tea",
                         "listen", "cheer", "share"],
                "proactive_per_day": 0,
                "prompt": "你对他没什么好脸色：话短、带刺，不主动搭话，也不做任何亲昵动作。",
            },
            {
                "name": "冷淡",
                "min_affinity": -40.0,
                "max_affinity": -10.0,
                "address": "你",
                "deny": ["hug", "kiss", "pat", "selfie", "leg_photo", "pour_tea"],
                "proactive_per_day": 0,
                "prompt": "你对他淡淡的：客气但不热络，不主动找他，也不撒娇。",
            },
            {
                "name": "客气",
                "min_affinity": -10.0,
                "max_affinity": 10.0,
                "address": "你",
                "deny": ["hug", "kiss", "pat", "selfie", "leg_photo"],
                "proactive_per_day": 0,
                "prompt": "你们还不熟：礼貌、有分寸，不主动提私事，不撒娇，也不动手动脚。",
            },
            {
                "name": "熟人",
                "min_affinity": 10.0,
                "max_affinity": 30.0,
                "address": "你",
                "deny": ["hug", "kiss", "pat", "selfie", "leg_photo"],
                "proactive_per_day": 1,
                "prompt": "算是熟人了：可以闲聊、开玩笑，但别越界——不撒娇、不贴贴。",
            },
            {
                "name": "朋友",
                "min_affinity": 30.0,
                "max_affinity": 55.0,
                "address": "你",
                "deny": ["hug", "kiss", "leg_photo"],
                "proactive_per_day": 2,
                "prompt": "你们是朋友：说话随意、会互相吐槽、可以拍一下摸一下头，但到抱抱亲亲就过了。",
            },
            {
                "name": "亲近",
                "min_affinity": 55.0,
                "max_affinity": 80.0,
                "address": "",
                "deny": ["leg_photo"],
                "proactive_per_day": 3,
                "prompt": "你跟他很亲近：会撒娇、会抱抱、会分享日常自拍，夜里他找你也会回。",
            },
            {
                "name": "特别的人",
                "min_affinity": 80.0,
                "max_affinity": 100.0,
                "address": "",
                "deny": [],
                "proactive_per_day": 4,
                "prompt": "他是你最特别的人：亲昵动作都可以，会吃醋、会闹脾气、也会主动找他。",
            },
        ],
    },
    "zones": [
        {
            "id": "home",
            "name": "家中",
            "note": "她自己的小窝，安静、私密、什么都有。",
            "icon": "home",
            "color": "#7FB2E5",
            "x": 80,
            "y": 80,
        },
        {
            "id": "street",
            "name": "商业街",
            "note": "人来人往、霓虹和招牌，什么都买得到，也最容易碰上新鲜事。",
            "icon": "shop",
            "color": "#E5A76B",
            "x": 320,
            "y": 80,
        },
        {
            "id": "school",
            "name": "学校",
            "note": "白天上课、放学就安静下来；图书馆、操场、天台都在里面。",
            "icon": "school",
            "color": "#6FBF8F",
            "x": 560,
            "y": 80,
        },
        {
            "id": "park",
            "name": "公园",
            "note": "树影、长椅、湖边长廊，走两步就能安静下来。",
            "icon": "tree",
            "color": "#7FC58F",
            "x": 320,
            "y": 280,
        },
        {
            "id": "seaside",
            "name": "海边",
            "note": "风大、浪声不停，去一趟要花点时间，但最让人放空。",
            "icon": "wave",
            "color": "#5FB3D4",
            "x": 560,
            "y": 280,
        },
    ],
    # 跨区门户：两端各写"某个区域里的哪个房间"，她在两个区域之间走动就靠这几条线
    "zone_edges": [
        {
            "id": "z_home_street",
            "from_zone": "home",
            "to_zone": "street",
            "from_node": "lobby",
            "to_node": "street_gate",
            "ticks": 3,
            "bidirectional": True,
        },
        {
            "id": "z_home_park",
            "from_zone": "home",
            "to_zone": "park",
            "from_node": "lobby",
            "to_node": "park_gate",
            "ticks": 4,
            "bidirectional": True,
        },
        {
            "id": "z_street_school",
            "from_zone": "street",
            "to_zone": "school",
            "from_node": "street_gate",
            "to_node": "school_gate",
            "ticks": 2,
            "bidirectional": True,
        },
        {
            "id": "z_street_park",
            "from_zone": "street",
            "to_zone": "park",
            "from_node": "street_gate",
            "to_node": "park_gate",
            "ticks": 3,
            "bidirectional": True,
        },
        {
            "id": "z_park_seaside",
            "from_zone": "park",
            "to_zone": "seaside",
            "from_node": "park_gate",
            "to_node": "boardwalk",
            "ticks": 3,
            "bidirectional": True,
        },
    ],
    "nodes": [
        {
            "id": "bedroom",
            "name": "卧室",
            "zone_id": "home",
            "x": 40,
            "y": 60,
            "icon": "bed",
            "color": "#8B7DD8",
            "prompt": "安静、私密、适合休息。在这里你更容易困倦，也更容易做梦。",
            "nickname_text": "在卧室",
            "atmosphere": {
                "calm": 0.9,
                "intimacy": 0.8,
                "visibility": 0.2,
                "liveliness": 0.1,
                "loneliness": 0.6,
                "curiosity": 0.2,
            },
            "preset_memories": [
                {
                    "content": "在这里做过一个很温柔的梦",
                    "scope": "persona",
                    "emotion": "温柔",
                    "weight": 0.6,
                }
            ],
        },
        {
            "id": "study",
            "name": "书房",
            "zone_id": "home",
            "x": 220,
            "y": 60,
            "icon": "book",
            "color": "#4C8BF5",
            "prompt": "堆着书和旧笔记，桌上有一台电脑。适合看书、上网、想事情。",
            "nickname_text": "在书房",
            "atmosphere": {
                "calm": 0.7,
                "intimacy": 0.4,
                "visibility": 0.5,
                "liveliness": 0.3,
                "loneliness": 0.3,
                "curiosity": 0.8,
            },
            "preset_memories": [
                {
                    "content": "在这张桌子前查过很多奇怪的问题",
                    "scope": "node",
                    "emotion": "好奇",
                    "weight": 0.5,
                }
            ],
        },
        {
            "id": "window",
            "name": "窗边",
            "zone_id": "home",
            "x": 400,
            "y": 60,
            "icon": "window",
            "color": "#67C2A5",
            "prompt": "能看见外面天色和偶尔路过的云。发呆最合适的地方。",
            "nickname_text": "在窗边",
            "atmosphere": {
                "calm": 0.8,
                "intimacy": 0.6,
                "visibility": 0.6,
                "liveliness": 0.3,
                "loneliness": 0.6,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "bar",
            "name": "吧台",
            "zone_id": "home",
            "x": 220,
            "y": 240,
            "icon": "cup",
            "color": "#E0A458",
            "prompt": "有水、杯子和一点零食。适合边喝东西边和人聊天。",
            "nickname_text": "在吧台",
            "atmosphere": {
                "calm": 0.5,
                "intimacy": 0.7,
                "visibility": 0.7,
                "liveliness": 0.7,
                "loneliness": 0.3,
                "curiosity": 0.4,
            },
            "preset_memories": [],
        },
        {
            "id": "kitchen",
            "name": "厨房",
            "zone_id": "home",
            "x": 400,
            "y": 240,
            "icon": "pot",
            "color": "#D9805F",
            "prompt": "有锅、有冰箱、有一排调料。做饭的时候你心情通常会变好，桌上很快就有热的东西。",
            "nickname_text": "在厨房",
            "atmosphere": {
                "calm": 0.4,
                "intimacy": 0.6,
                "visibility": 0.4,
                "liveliness": 0.6,
                "loneliness": 0.2,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "lobby",
            "name": "客厅",
            "zone_id": "home",
            "x": 40,
            "y": 240,
            "icon": "sofa",
            "color": "#B0B7C3",
            "prompt": "沙发和电视都在这儿，谁来了都先坐这儿；连接所有房间的地方。",
            "nickname_text": "在客厅",
            "atmosphere": {
                "calm": 0.5,
                "intimacy": 0.6,
                "visibility": 0.9,
                "liveliness": 0.9,
                "loneliness": 0.3,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "bathroom",
            "name": "浴室",
            "zone_id": "home",
            "x": 40,
            "y": 380,
            "icon": "bath",
            "color": "#7FA8D9",
            "prompt": "热水、雾气和一面镜子；关上门就是她自己的地方，适合把一天的疲惫泡掉。",
            "nickname_text": "在浴室",
            "atmosphere": {
                "calm": 0.7,
                "intimacy": 0.9,
                "visibility": 0.1,
                "liveliness": 0.2,
                "loneliness": 0.3,
                "curiosity": 0.3,
            },
            "preset_memories": [],
        },
        {
            "id": "street_gate",
            "name": "街口",
            "zone_id": "street",
            "x": 40,
            "y": 60,
            "icon": "road",
            "color": "#E5A76B",
            "prompt": "一出小区就是这儿：招牌、外卖车、来来往往的人，什么都看得见。",
            "nickname_text": "在街口",
            "atmosphere": {
                "calm": 0.3,
                "intimacy": 0.3,
                "visibility": 1.0,
                "liveliness": 0.9,
                "loneliness": 0.2,
                "curiosity": 0.6,
            },
            "preset_memories": [],
        },
        {
            "id": "mall",
            "name": "商场",
            "zone_id": "street",
            "x": 240,
            "y": 60,
            "icon": "shop",
            "color": "#D98CB3",
            "prompt": "一层化妆品、一层衣服，冷气很足；逛久了腿会酸，但总有新东西看。",
            "nickname_text": "在商场",
            "atmosphere": {
                "calm": 0.4,
                "intimacy": 0.3,
                "visibility": 0.9,
                "liveliness": 0.8,
                "loneliness": 0.2,
                "curiosity": 0.7,
            },
            "preset_memories": [],
        },
        {
            "id": "snacks",
            "name": "小吃街",
            "zone_id": "street",
            "x": 440,
            "y": 60,
            "icon": "bowl",
            "color": "#E08A5F",
            "prompt": "一排小摊挤在一起，油烟和香味混着往上飘，越晚越热闹。",
            "nickname_text": "在小吃街",
            "atmosphere": {
                "calm": 0.3,
                "intimacy": 0.4,
                "visibility": 0.9,
                "liveliness": 1.0,
                "loneliness": 0.1,
                "curiosity": 0.6,
            },
            "preset_memories": [],
        },
        {
            "id": "school_gate",
            "name": "校门口",
            "zone_id": "school",
            "x": 40,
            "y": 60,
            "icon": "gate",
            "color": "#6FBF8F",
            "prompt": "放学时间最吵，平时只剩保安、自行车和一排告示栏。",
            "nickname_text": "在校门口",
            "atmosphere": {
                "calm": 0.4,
                "intimacy": 0.3,
                "visibility": 0.9,
                "liveliness": 0.7,
                "loneliness": 0.2,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "classroom",
            "name": "教室",
            "zone_id": "school",
            "x": 240,
            "y": 60,
            "icon": "desk",
            "color": "#74A9E0",
            "prompt": "黑板、粉笔灰、一排排课桌；上课时有人念书，没人的时候特别安静。",
            "nickname_text": "在教室",
            "atmosphere": {
                "calm": 0.6,
                "intimacy": 0.2,
                "visibility": 0.7,
                "liveliness": 0.5,
                "loneliness": 0.2,
                "curiosity": 0.8,
            },
            "preset_memories": [],
        },
        {
            "id": "library",
            "name": "图书馆",
            "zone_id": "school",
            "x": 440,
            "y": 60,
            "icon": "book",
            "color": "#5C9E7E",
            "prompt": "书架很高，只有翻书声和空调声；角落里有几台公共电脑能查资料。",
            "nickname_text": "在图书馆",
            "atmosphere": {
                "calm": 0.8,
                "intimacy": 0.2,
                "visibility": 0.5,
                "liveliness": 0.3,
                "loneliness": 0.3,
                "curiosity": 0.9,
            },
            "preset_memories": [],
        },
        {
            "id": "playground",
            "name": "操场",
            "zone_id": "school",
            "x": 240,
            "y": 240,
            "icon": "run",
            "color": "#8FBF5F",
            "prompt": "红色跑道围着一片草，白天有人打球跑步，晚上只剩路灯。",
            "nickname_text": "在操场",
            "atmosphere": {
                "calm": 0.3,
                "intimacy": 0.2,
                "visibility": 1.0,
                "liveliness": 0.9,
                "loneliness": 0.2,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "rooftop",
            "name": "天台",
            "zone_id": "school",
            "x": 440,
            "y": 240,
            "icon": "roof",
            "color": "#9AA7B8",
            "prompt": "风比下面大得多，能看见整片楼顶和远处的云，适合一个人待着。",
            "nickname_text": "在天台",
            "atmosphere": {
                "calm": 0.7,
                "intimacy": 0.4,
                "visibility": 0.4,
                "liveliness": 0.2,
                "loneliness": 0.7,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "park_gate",
            "name": "公园大门",
            "zone_id": "park",
            "x": 40,
            "y": 60,
            "icon": "tree",
            "color": "#7FC58F",
            "prompt": "两排行道树夹着一条石板路，进去就是另一套节奏。",
            "nickname_text": "在公园",
            "atmosphere": {
                "calm": 0.6,
                "intimacy": 0.3,
                "visibility": 0.8,
                "liveliness": 0.6,
                "loneliness": 0.3,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "park_bench",
            "name": "长椅",
            "zone_id": "park",
            "x": 240,
            "y": 60,
            "icon": "bench",
            "color": "#A8C97F",
            "prompt": "树荫下的木长椅，常有人在这儿喂猫、下棋、看孩子跑来跑去。",
            "nickname_text": "在长椅",
            "atmosphere": {
                "calm": 0.8,
                "intimacy": 0.4,
                "visibility": 0.6,
                "liveliness": 0.4,
                "loneliness": 0.6,
                "curiosity": 0.4,
            },
            "preset_memories": [],
        },
        {
            "id": "park_lake",
            "name": "湖边",
            "zone_id": "park",
            "x": 440,
            "y": 60,
            "icon": "water",
            "color": "#6FBFD6",
            "prompt": "一圈木栈道绕着湖，水面总在轻轻晃，站久了会想很多事。",
            "nickname_text": "在湖边",
            "atmosphere": {
                "calm": 0.9,
                "intimacy": 0.5,
                "visibility": 0.5,
                "liveliness": 0.3,
                "loneliness": 0.6,
                "curiosity": 0.5,
            },
            "preset_memories": [],
        },
        {
            "id": "boardwalk",
            "name": "海滨步道",
            "zone_id": "seaside",
            "x": 40,
            "y": 60,
            "icon": "wave",
            "color": "#5FB3D4",
            "prompt": "木板路沿着一整条海岸线，栏杆上都是盐渍，风一直不停。",
            "nickname_text": "在海边",
            "atmosphere": {
                "calm": 0.7,
                "intimacy": 0.3,
                "visibility": 0.8,
                "liveliness": 0.5,
                "loneliness": 0.4,
                "curiosity": 0.6,
            },
            "preset_memories": [],
        },
        {
            "id": "beach",
            "name": "沙滩",
            "zone_id": "seaside",
            "x": 240,
            "y": 60,
            "icon": "sand",
            "color": "#E8C87A",
            "prompt": "细沙、一道道浪线、散落的贝壳；风一吹，头发全乱。",
            "nickname_text": "在沙滩",
            "atmosphere": {
                "calm": 0.8,
                "intimacy": 0.4,
                "visibility": 0.7,
                "liveliness": 0.6,
                "loneliness": 0.4,
                "curiosity": 0.7,
            },
            "preset_memories": [],
        },
        {
            "id": "rocks",
            "name": "礁石",
            "zone_id": "seaside",
            "x": 440,
            "y": 60,
            "icon": "rock",
            "color": "#8C9AA6",
            "prompt": "浪拍在石头上溅起白花，站久了鞋会湿，安静得只剩水声。",
            "nickname_text": "在礁石",
            "atmosphere": {
                "calm": 0.7,
                "intimacy": 0.5,
                "visibility": 0.4,
                "liveliness": 0.2,
                "loneliness": 0.7,
                "curiosity": 0.6,
            },
            "preset_memories": [],
        },
    ],
    "edges": [
        {"id": "e_bed_lobby", "from": "bedroom", "to": "lobby", "ticks": 1, "bidirectional": True},
        {"id": "e_study_lobby", "from": "study", "to": "lobby", "ticks": 1, "bidirectional": True},
        {"id": "e_bar_lobby", "from": "bar", "to": "lobby", "ticks": 1, "bidirectional": True},
        {"id": "e_window_study", "from": "window", "to": "study", "ticks": 1, "bidirectional": True},
        {"id": "e_bar_kitchen", "from": "bar", "to": "kitchen", "ticks": 1, "bidirectional": True},
        {"id": "e_bath_lobby", "from": "bathroom", "to": "lobby", "ticks": 1, "bidirectional": True},
        {"id": "e_gate_mall", "from": "street_gate", "to": "mall", "ticks": 2, "bidirectional": True},
        {"id": "e_gate_snacks", "from": "street_gate", "to": "snacks", "ticks": 2, "bidirectional": True},
        {"id": "e_mall_snacks", "from": "mall", "to": "snacks", "ticks": 3, "bidirectional": True},
        {"id": "e_school_gate_class", "from": "school_gate", "to": "classroom", "ticks": 1, "bidirectional": True},
        {"id": "e_class_library", "from": "classroom", "to": "library", "ticks": 2, "bidirectional": True},
        {"id": "e_class_playground", "from": "classroom", "to": "playground", "ticks": 2, "bidirectional": True},
        {"id": "e_playground_rooftop", "from": "playground", "to": "rooftop", "ticks": 2, "bidirectional": True},
        {"id": "e_park_gate_bench", "from": "park_gate", "to": "park_bench", "ticks": 2, "bidirectional": True},
        {"id": "e_park_gate_lake", "from": "park_gate", "to": "park_lake", "ticks": 3, "bidirectional": True},
        {"id": "e_bench_lake", "from": "park_bench", "to": "park_lake", "ticks": 1, "bidirectional": True},
        {"id": "e_boardwalk_beach", "from": "boardwalk", "to": "beach", "ticks": 1, "bidirectional": True},
        {"id": "e_beach_rocks", "from": "beach", "to": "rocks", "ticks": 2, "bidirectional": True},
    ],
    "actions": [
        # ---------------- 表达类 ----------------
        {
            "id": "say",
            "builtin": True,
            "name": "说话",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "group",
            "visible": True,
            "priority": 1,
            "on_complete": {"effects": {"affect": "+0.06", "boredom": "-0.03"}},
            "description": "把想说的话发到群里。",
        },
        {
            "id": "think",
            "builtin": True,
            "name": "想事情",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "none",
            "visible": False,
            "priority": 3,
            "description": "在心里想一件事，会变成这个地点的内心记忆。",
        },
        {
            "id": "share",
            "builtin": True,
            "name": "分享",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "group",
            "visible": True,
            "preconditions": {},
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.10", "loneliness": "-0.05"}},
            "description": "把刚刚的见闻分享到群里。受每小时分享次数限制。",
        },
        {
            "id": "poke",
            "builtin": True,
            "name": "戳一戳",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "visible": False,
            "preconditions": {},
            "priority": 4,
            "template": "（{bot}戳了戳{user}）",
            "desc_mode": "brief",
            "on_complete": {"effects": {"affect": "+0.06", "loneliness": "-0.04"}},
            "description": "戳一下某个群友（QQ 的「戳一戳」）。不用说话就能搭个话，适合提醒对方、或者不知道说什么的时候用。目标填对方的 id。",
        },
        {
            "id": "recall",
            "builtin": True,
            "name": "回想",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "none",
            "visible": False,
            "preconditions": {},
            "priority": 4,
            "on_complete": {"trigger": "none"},
            "description": (
                "主动回忆。想回忆某段经历、某个地点（或某个区域）发生过的事，"
                "或者无聊、孤单时想翻一翻美好的记忆，都可以用它。"
                "只填 intent 说清想回忆什么，例如「想想上次在厨房做饭的事」"
                "或「回忆一下公园里的事」；想指定地点就填 target_node。"
                "**回忆完不需要再写别的动作**：系统会去记忆里翻，"
                "翻完带着结果再问你一次，那时候你再说话。"
                "翻旧账时如果发现**关于某个人的信息或者你们的关系已经变了**"
                "（称呼、喜好、约定、亲疏），可以顺手用 remember 把它改掉。"
            ),
        },
        {
            "id": "remember",
            "builtin": True,
            "name": "记住",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "none",
            "visible": False,
            "preconditions": {},
            "priority": 4,
            "on_complete": {"trigger": "none"},
            "description": (
                "把**这一刻你判断值得记的事**当场写进通讯录（关于某个人的事实、"
                "你们的关系、你对他的好感变化）。只在他真的说清楚了、"
                "而且你能引用他的原话时才用；日常寒暄不要用。参数写在 params 里："
                '"user" 写他的 QQ 号，"text" 一句话说清是什么事，'
                '"evidence" 填**他的原话**（必填，没有原话就不写），'
                '"kind" 选 喜好/厌恶/习惯/基本信息/关系/约定/近况；'
                "改关系再给 \"bond\"（例如 朋友 / 闺蜜 / 主人 / 男友 / 讨厌的人），"
                "想调好感度再给 \"affinity_delta\"（-10~10 的一个数）。例如 "
                '{"type":"remember","params":{"user":"2692047521","text":"爱喝冰美式，不加糖",'
                '"evidence":"今天又灌了一杯冰美式","kind":"喜好"}}。'
                "**写完不用再说什么**：想顺口提一句就另外写一个 say。"
            ),
        },
        {
            "id": "schedule_list",
            "builtin": True,
            "name": "查看日程",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "none",
            "visible": False,
            "preconditions": {},
            "priority": 4,
            "on_complete": {"trigger": "none"},
            "description": (
                "看看自己每天安排好要做的事。不用填 intent；"
                "看完系统会带着日程表再问你一次，你那时候再说话。"
            ),
        },
        {
            "id": "schedule_add",
            "builtin": True,
            "name": "添加日程",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "none",
            "visible": False,
            "preconditions": {},
            "priority": 4,
            "on_complete": {"trigger": "none"},
            "description": (
                "给自己加一条日程（到了点自动做某串动作）。"
                "把打算写成一句自然语言填进 intent，例如「每天早上七点去书房查新闻」；"
                "**只是提醒**（到点说一句话）时，再给两个参数："
                'params.at 写什么时候（「10 分钟后」「21:30」「晚上八点」都行），'
                "params.say 写到时候要说的话（1~2 句），例如 "
                '{"type":"schedule_add","intent":"十分钟后提醒主人喝水",'
                '"params":{"at":"10 分钟后","say":["该喝水啦 笨蛋"]}}；'
                "只做一次的事要说清哪天哪一刻、以及为什么要做，"
                "例如「明天下午三点去收衣服，因为主人说下午可能下雨」。"
                "**加完不用再写别的动作**：系统会替你把时间、星期和动作链填好，再带着结果问你一次。"
            ),
        },
        {
            "id": "schedule_remove",
            "builtin": True,
            "name": "删除日程",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "none",
            "visible": False,
            "preconditions": {},
            "priority": 4,
            "on_complete": {"trigger": "none"},
            "description": (
                "删掉自己之前加的一条日程。在 intent 里说清是哪条（时间或名字）即可，"
                "例如「把七点查新闻那条删了」。**注意**：用户自己配的日程她删不掉，只能删自己加的。"
            ),
        },
        {
            "id": "sing",
            "name": "哼歌",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "group",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.08", "boredom": "-0.05"}},
            "description": "随口哼两句，心情会好一点。",
        },
        # ---------------- 互动类（模板 + 数值联动） ----------------
        {
            "id": "hug",
            "name": "抱抱",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}抱了你一下）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"loneliness": "-0.15", "affect": "+0.28"}},
            "description": "抱一下某个人，会让你们都放松一点。",
        },
        {
            "id": "kiss",
            "name": "亲亲",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}在你脸上轻轻亲了一下）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"loneliness": "-0.20", "affect": "+0.35"}},
            "description": "亲一下某个人。只在关系亲近的时候用。",
        },
        {
            "id": "pat",
            "name": "摸摸头",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}摸了摸{user}的头）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"loneliness": "-0.10", "affect": "+0.16"}},
            "description": "摸摸对方的头，适合安慰人的时候用。",
        },
        {
            "id": "smile",
            "name": "笑",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}对着你笑了笑）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.06"}},
            "description": "对某个人笑一下。",
        },
        {
            "id": "wave",
            "name": "挥手",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}朝你挥了挥手）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.06"}},
            "description": "对某个人挥手打招呼，适合刚进门或要离开的时候。",
        },
        {
            "id": "pour_tea",
            "name": "倒茶提醒喝水",
            "category": "instant",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["bar", "kitchen", "lobby"],
            "target_type": "user",
            "template": "（{bot}给你倒了杯茶，顺嘴提醒你去喝口水）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.10", "loneliness": "-0.05"}},
            "description": "给某个人倒杯茶，顺便提醒他喝口水（他容易忘）。在吧台、厨房或客厅可用。",
        },
        {
            "id": "listen",
            "name": "听你说",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "user",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"loneliness": "-0.08", "affect": "+0.12"}},
            "description": "认真听某个人说话，并回应一句。",
        },
        {
            "id": "cheer",
            "name": "打气",
            "category": "instant",
            "llm_level": "single",
            "scope": "global",
            "target_type": "user",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.10"}},
            "description": "给某个人加油打气，说一句鼓励的话。",
        },
        # ---- 互动动作（按亲密度铺开：够不着的人由她自己克制，见分级说明） ----
        # 「看一眼名字就知道干嘛」的动作用 desc_mode=brief，不往提示词里塞说明
        {
            "id": "nod",
            "name": "点头",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "none",
            "template": "（{bot}点了点头）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.06"}},
            "description": "点头表示认同。",
        },
        {
            "id": "shake_head",
            "name": "摇头",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "none",
            "template": "（{bot}摇了摇头）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.04"}},
            "description": "摇头表示不同意、或者拿对方没办法。",
        },
        {
            "id": "clap",
            "name": "鼓掌",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "none",
            "template": "（{bot}鼓了鼓掌，给你捧个场）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.10"}},
            "description": "给对方捧个场。",
        },
        {
            "id": "head_tilt",
            "name": "歪头",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "none",
            "template": "（{bot}歪着头看你）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.06"}},
            "description": "歪头看着对方，表示没听懂或在打量。",
        },
        {
            "id": "blink",
            "name": "眨眼",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}朝{user}眨了眨眼）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.08"}},
            "description": "朝对方眨眨眼，俏皮一下。",
        },
        {
            "id": "high_five",
            "name": "击掌",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}和{user}碰了下拳头）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.14", "loneliness": "-0.05"}},
            "description": "和对方击掌，庆祝或者打个招呼。",
        },
        {
            "id": "pat_shoulder",
            "name": "拍肩",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}拍了拍{user}的肩）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.10", "loneliness": "-0.06"}},
            "description": "拍拍对方的肩膀，安慰或者鼓劲。",
        },
        {
            "id": "hand_tissue",
            "name": "递纸巾",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}递了张纸巾给{user}）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.08", "loneliness": "-0.08"}},
            "description": "对方难受时递张纸巾。",
        },
        {
            "id": "give_snack",
            "name": "分你一半",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}把吃的分了一半给{user}）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.12", "loneliness": "-0.06"}},
            "description": "把手里的零食分给对方一半。",
        },
        # ---- 朋友档：打闹（都是玩闹口吻，不带伤害） ----
        {
            "id": "ruffle_hair",
            "name": "揉乱头发",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}把{user}的头发揉乱了）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.18", "loneliness": "-0.10"}},
            "description": "把对方的头发揉乱，闹一下。",
        },
        {
            "id": "tug_sleeve",
            "name": "扯衣角",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}揪了揪{user}的衣角）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.14", "loneliness": "-0.08"}},
            "description": "揪对方的衣角，想让他看过来。",
        },
        {
            "id": "bump_shoulder",
            "name": "撞肩膀",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}用肩膀撞了{user}一下）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.16", "loneliness": "-0.06"}},
            "description": "用肩膀撞对方一下，闹着玩。",
        },
        {
            "id": "pinch_nose",
            "name": "捏鼻子",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}捏了下{user}的鼻子）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.16", "loneliness": "-0.06"}},
            "description": "捏一下对方的鼻子，损他一下。",
        },
        {
            "id": "cold_hands",
            "name": "冰手偷袭",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}冰凉的手塞进{user}的脖子里）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.20", "loneliness": "-0.08"}},
            "description": "把冰凉的手塞进对方脖子上偷袭。",
        },
        {
            "id": "bite_shoulder",
            "name": "咬肩膀",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}啊呜一口咬在{user}肩膀上，没使劲）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.20", "loneliness": "-0.10"}},
            "description": "轻轻咬对方肩膀一口，闹脾气或者撒气。",
        },
        {
            "id": "bite_wrist",
            "name": "咬手腕",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}抓住{user}的手腕轻轻咬了一口）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.22", "loneliness": "-0.10"}},
            "description": "抓住对方的手腕轻咬一口，带点小威胁的撒娇。",
        },
        # ---- 亲近档：亲昵 ----
        {
            "id": "hold_hands",
            "name": "牵手",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}牵住了{user}的手）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.24", "loneliness": "-0.16"}},
            "description": "牵对方的手。",
        },
        {
            "id": "lean_on",
            "name": "靠肩膀",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}靠在{user}肩上）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.24", "loneliness": "-0.20"}},
            "description": "靠在对方肩膀上。",
        },
        {
            "id": "nuzzle",
            "name": "蹭蹭",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}凑过去蹭了蹭{user}）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.26", "loneliness": "-0.18"}},
            "description": "凑过去蹭对方，撒娇。",
        },
        {
            "id": "pinch_cheek",
            "name": "捏脸",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}捏了捏{user}的脸）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.22", "loneliness": "-0.12"}},
            "description": "捏对方的脸。",
        },
        {
            "id": "close_eyes",
            "name": "闭上眼",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}闭上眼，凑近了些）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.28", "loneliness": "-0.18"}},
            "description": "闭上眼睛凑近对方，等一个亲亲。",
        },
        {
            "id": "kiss_forehead",
            "name": "亲额头",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}在{user}额头上轻轻亲了一下）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.28", "loneliness": "-0.24"}},
            "description": "亲一下对方的额头。",
        },
        {
            "id": "wipe_tears",
            "name": "擦眼泪",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}替{user}擦了擦眼角）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.18", "loneliness": "-0.20"}},
            "description": "对方难过时替他擦眼泪。",
        },
        {
            "id": "massage",
            "name": "揉肩",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}替{user}揉了揉肩）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.16", "loneliness": "-0.16"}},
            "description": "替对方揉揉肩，让他放松一点。",
        },
        {
            "id": "drape_coat",
            "name": "披外套",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}把外套披在{user}身上）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.18", "loneliness": "-0.18"}},
            "description": "把自己的外套披在对方身上。",
        },
        # ---- 特别的人档：最亲密（依然不越界） ----
        {
            "id": "interlock",
            "name": "十指相扣",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}和{user}十指扣在一起）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.30", "loneliness": "-0.26"}},
            "description": "和对方十指相扣。",
        },
        {
            "id": "nestle",
            "name": "钻怀里",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}钻进{user}怀里埋着不动）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.30", "loneliness": "-0.28"}},
            "description": "钻进对方怀里赖着。",
        },
        {
            "id": "feed_bite",
            "name": "投喂",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}把吃得到{user}嘴边）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.26", "loneliness": "-0.18"}},
            "description": "把吃的递到对方嘴边喂他。",
        },
        {
            "id": "kiss_lips",
            "name": "接吻",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}凑过去吻了{user}）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 5,
            "on_complete": {"effects": {"affect": "+0.34", "loneliness": "-0.30"}},
            "description": "和对方接吻，只对最特别的人用。",
        },
        {
            "id": "whisper_ear",
            "name": "耳边说",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "user",
            "template": "（{bot}凑到{user}耳边说了句什么）",
            "desc_mode": "brief",
            "visible": True,
            "priority": 4,
            "on_complete": {"effects": {"affect": "+0.24", "loneliness": "-0.14"}},
            "description": "凑到对方耳边说悄悄话，说完再正常说一句。",
        },
        {
            "id": "stretch",
            "name": "伸懒腰",
            "category": "instant",
            "llm_level": "template",
            "scope": "global",
            "target_type": "none",
            "template": "（{bot}伸了个懒腰）",
            "visible": True,
            "priority": 3,
            "on_complete": {"effects": {"energy": "+0.02"}},
            "description": "伸个懒腰，动作会发到群里。",
        },
        # ---------------- 生活类（时长交给大模型 + 按分钟结算） ----------------
        {
            "id": "walk_to",
            "nickname_text": "移动中",
            "builtin": True,
            "name": "移动",
            "category": "continuous",
            "llm_level": "template",
            "scope": "global",
            "target_type": "none",
            "duration": 0,
            "interruptible": True,
            "visible": False,
            "priority": 2,
            "during": {"state": "walking"},
            "description": "走到另一个地点或某个人身边。耗时由地图上的连线决定。",
        },
        {
            "id": "sleep",
            "nickname_text": "睡觉中",
            "builtin": True,
            "name": "睡觉",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["bedroom"],
            "target_type": "none",
            "duration": 28800,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "sleeping"},
            "on_complete": {
                "trigger": "none",
                "effects": {"energy": "=0.95", "mood": "mood:清爽"},
            },
            "visible": False,
            "priority": 8,
            "description": (
                "睡一整晚恢复精力（约 8 小时，夜里或凌晨、实在撑不住时用），需要先回到卧室。"
                "白天只是犯困就小睡一会儿，别在白天睡整觉。"
            ),
        },
        {
            "id": "nap",
            "nickname_text": "小睡中",
            "name": "小睡",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["bedroom", "lobby"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 3600,
            "interruptible": True,
            "during": {"state": "napping"},
            "on_complete": {
                "trigger": "none",
                "effects_per_minute": {"energy": "+0.0015"},
            },
            "visible": False,
            "priority": 6,
            "description": (
                "白天犯困时打个盹（10 分钟到 1 小时，睡多久由你自己决定），缓过来接着过；"
                "睡得越久精力恢复越多。"
            ),
        },
        {
            # ---------------- 内置生图动作（默认停用） ----------------
            # 它们都靠"别的插件提供的指令"出图，所以默认不启用：
            # 没装对应插件时启用只会让她白说一句。
            "id": "selfie",
            "nickname_text": "",
            "builtin": True,
            "name": "自拍",
            "category": "continuous",
            "llm_level": "command",
            "scope": "global",
            "allowed_nodes": [],
            "target_type": "none",
            "duration": 60,
            "duration_mode": "fixed",
            "duration_min": 60,
            "duration_max": 60,
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "during": {"state": ""},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "你刚发了一张自拍照片，用一句自然的话带过（别描述构图、别念参数）。",
                "effects": {"affect": "+0.10"},
            },
            "template": "",
            "nickname_text": "",
            "tool_name": "",
            "tool_names": [],
            "tool_fallbacks": [],
            "tool_mode": "sequence",
            "tool_flow": "simple",
            "reader_tool_names": [],
            "search_depth": "standard",
            "search_max_queries": 3,
            "search_max_reads": 3,
            "search_rounds": 2,
            "search_topic": "",
            "search_query_template": "",
            "search_cite": False,
            "trigger_command": "自拍",
            "quota": {"day": 5},
            "trigger_hint": (
                "可以补一句画面描述（描述里不要有空格），例如：/自拍 对着镜头比耶。"
            ),
            "group": "",
            "event_usable": "deny",
            "visible": False,
            "priority": 5,
            "enabled": False,
            "description": (
                "拍一张自己的照片发出来。意图里写清画面内容和此刻所处的环境，"
                "例如「在书房对着镜头比耶」；出图需要时间，可以用摆姿势之类的说法带过。"
            ),
        },
        {
            "id": "take_photo",
            "builtin": True,
            "name": "拍照",
            "category": "continuous",
            "llm_level": "command",
            "scope": "global",
            "allowed_nodes": [],
            "target_type": "none",
            "duration": 60,
            "duration_mode": "fixed",
            "duration_min": 60,
            "duration_max": 60,
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "during": {"state": ""},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "你刚刚拍了张照片发出来，用一句自然的话带过。",
                "effects": {"affect": "+0.05"},
            },
            "template": "",
            "nickname_text": "",
            "tool_name": "",
            "tool_names": [],
            "tool_fallbacks": [],
            "tool_mode": "sequence",
            "tool_flow": "simple",
            "reader_tool_names": [],
            "search_depth": "standard",
            "search_max_queries": 3,
            "search_max_reads": 3,
            "search_rounds": 2,
            "search_topic": "",
            "search_query_template": "",
            "search_cite": False,
            "trigger_command": "看看你",
            "quota": {"day": 5},
            "trigger_hint": (
                "意图里写清要拍的内容，会把意图拼进参数，例如：/看看你 和湖边的风景合影。"
            ),
            "group": "",
            "event_usable": "deny",
            "visible": False,
            "priority": 5,
            "enabled": False,
            "description": (
                "拍一张照片：可以只拍眼前的东西，也可以把自己和它拍在一起。"
                "意图里写清画面内容。"
            ),
        },
        {
            "id": "leg_photo",
            "builtin": True,
            "name": "拍腿的照片",
            "category": "continuous",
            "llm_level": "command",
            "scope": "global",
            "allowed_nodes": [],
            "target_type": "user",
            "duration": 60,
            "duration_mode": "fixed",
            "duration_min": 60,
            "duration_max": 60,
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "during": {"state": ""},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "你刚发了一张照片，用一句自然的话带过（别描述构图）。",
                "effects": {"affect": "+0.30"},
            },
            "template": "",
            "nickname_text": "",
            "tool_name": "",
            "tool_names": [],
            "tool_fallbacks": [],
            "tool_mode": "sequence",
            "tool_flow": "simple",
            "reader_tool_names": [],
            "search_depth": "standard",
            "search_max_queries": 3,
            "search_max_reads": 3,
            "search_rounds": 2,
            "search_topic": "",
            "search_query_template": "",
            "search_cite": False,
            "trigger_command": "看看腿",
            "quota": {"day": 5},
            "trigger_hint": "不需要参数，直接输出指令本身。",
            "group": "",
            "event_usable": "deny",
            "visible": False,
            "priority": 5,
            "enabled": False,
            "description": (
                "拍一张腿部特写的照片发给对方（只对亲近的人用）。"
                "出图需要时间，可以用摆个姿势之类的说法带过。"
            ),
        },
        {
            "id": "change_clothes",
            "builtin": True,
            "name": "换一套衣服",
            "category": "continuous",
            "llm_level": "command",
            "scope": "global",
            "allowed_nodes": [],
            "target_type": "none",
            "duration": 60,
            "duration_mode": "fixed",
            "duration_min": 60,
            "duration_max": 60,
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "during": {"state": ""},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "提一下你今天换的穿搭和此刻的心情，语气自然，像在分享。",
                "effects": {"affect": "+0.05"},
            },
            "template": "",
            "nickname_text": "",
            "tool_name": "",
            "tool_names": [],
            "tool_fallbacks": [],
            "tool_mode": "sequence",
            "tool_flow": "simple",
            "reader_tool_names": [],
            "search_depth": "standard",
            "search_max_queries": 3,
            "search_max_reads": 3,
            "search_rounds": 2,
            "search_topic": "",
            "search_query_template": "",
            "search_cite": False,
            "trigger_command": "形象刷新",
            "quota": {"day": 5},
            "trigger_hint": "不需要参数，直接输出指令本身。",
            "group": "",
            "event_usable": "deny",
            "visible": False,
            "priority": 5,
            "enabled": False,
            "description": "换一套今天的穿搭（会影响之后拍照时的形象）。不需要参数。",
        },
        {
            "id": "make_video",
            "builtin": True,
            "name": "录视频",
            "category": "continuous",
            "llm_level": "command",
            "scope": "global",
            "allowed_nodes": [],
            "target_type": "none",
            "duration": 60,
            "duration_mode": "fixed",
            "duration_min": 60,
            "duration_max": 60,
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "during": {"state": ""},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "你刚发了一段视频，用一句自然的话带过（别描述分镜、别念参数）。",
                "effects": {"affect": "+0.10"},
            },
            "template": "",
            "nickname_text": "",
            "tool_name": "",
            "tool_names": [],
            "tool_fallbacks": [],
            "tool_mode": "sequence",
            "tool_flow": "simple",
            "reader_tool_names": [],
            "search_depth": "standard",
            "search_max_queries": 3,
            "search_max_reads": 3,
            "search_rounds": 2,
            "search_topic": "",
            "search_query_template": "",
            "search_cite": False,
            "trigger_command": "",
            "trigger_hint": (
                "把意图写详细：镜头拍什么、你在做什么动作、穿着什么、环境怎么样、"
                "想要什么氛围，一条说清（会拼进指令参数）。"
            ),
            "quota": {"day": 2},
            "group": "",
            "event_usable": "deny",
            "visible": False,
            "priority": 5,
            "enabled": False,
            "description": (
                "录一段视频发出来。意图里写清楚**场景、动作、服饰、镜头与氛围**"
                "（例如「夜里在天台，穿白色oversize卫衣，风吹着头发，镜头从背后慢慢推近」）；"
                "越具体越好，生成需要时间。"
            ),
        },
        {
            "id": "stare",
            "nickname_text": "发呆中",
            "name": "发呆",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["window", "rooftop", "park_bench", "park_lake", "beach", "rocks"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 300,
            "duration_max": 1800,
            "interruptible": True,
            "during": {"state": "staring"},
            "on_complete": {
                "trigger": "none",
                "effects_per_minute": {"loneliness": "+0.0015", "boredom": "-0.002"},
            },
            "visible": False,
            "priority": 4,
            "description": "对着窗外或远处发呆，发多久由你自己决定。待得越久越容易想起人。",
        },
        {
            "id": "read",
            "nickname_text": "看书",
            "name": "看书",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["study", "library"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 3600,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "reading"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": (
                    "说你刚在读什么、读到哪、有什么感想——**书名或题材、里面的内容要讲出来**；"
                    "上面「在读的书」里已经有就接着往下说，没有就这会儿定下来"
                ),
                "effects_per_minute": {"curiosity": "-0.0008", "boredom": "-0.0015"},
            },
            "state_slot": "reading",
            "state_label": "在读的书",
            "visible": False,
            "priority": 4,
            "description": "读一会儿书，读多久由你自己决定；读完可能想说点什么。",
        },
        {
            "id": "cook",
            "nickname_text": "做饭中",
            "name": "做饭",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["kitchen"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 900,
            "duration_max": 3600,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "cooking"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": (
                    "用第一人称随口说说刚做好的这道菜：做了什么、闻起来怎么样、你自己吃着什么感觉；"
                    "不要招呼或招揽别人来吃。**想拍一张就给这顿饭拍张照**——"
                    "在 actions 里紧接着排一个拍照动作（selfie），拍完再说话"
                ),
                "effects": {"mood": "mood:满足"},
                "effects_per_minute": {"energy": "-0.0012", "boredom": "-0.0025"},
            },
            "visible": False,
            "priority": 6,
            "description": "在厨房做饭，做多久由你自己决定；做好之后会想跟大家说说这顿饭。",
        },
        # ---- 浴室：一天里最私密的一段，也是"收拾自己"的地方 ----
        {
            "id": "shower",
            "nickname_text": "洗澡中",
            "name": "洗澡",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["bathroom"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 1800,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "showering"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "随口说一句洗完之后的感受：头发还湿着、身上轻快了点之类的，不用细讲过程",
                "effects": {"mood": "mood:放松"},
                "effects_per_minute": {"energy": "-0.0008", "affect": "+0.0006"},
            },
            "visible": False,
            "priority": 5,
            "description": "洗个澡，洗多久由你自己决定；洗完会舒服一点，也常想说一句。",
        },
        {
            "id": "bath_soak",
            "nickname_text": "泡澡中",
            "name": "泡澡",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["bathroom"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 900,
            "duration_max": 2700,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "soaking"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "泡得有点犯困时的一句心里话或感慨，可以提到水面、雾气、想事情",
                "effects": {"mood": "mood:懒洋洋"},
                "effects_per_minute": {
                    "affect": "-0.0004",
                    "valence": "+0.0004",
                    "loneliness": "+0.0012",
                },
            },
            "visible": False,
            "priority": 5,
            "description": "放一缸热水泡一会儿，泡多久由你自己决定；泡着泡着容易想人。",
        },
        {
            "id": "mirror",
            "name": "照镜子",
            "category": "instant",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["bathroom"],
            "target_type": "none",
            "visible": False,
            "priority": 3,
            "on_complete": {"effects": {"affect": "+0.05"}},
            "description": "在镜子前站一会儿，看看自己今天什么样（想顺便换套衣服或拍照也可以接着做）。",
        },
        # ---- 客厅：待客、追剧、瘫着 ----
        {
            "id": "watch_tv",
            "nickname_text": "追剧中",
            "name": "追剧",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["lobby"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 1800,
            "duration_max": 7200,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "watching"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": (
                    "说你刚在看什么、看到哪、什么感受——**剧名（可以自己起）、人物或剧情要讲出来**，"
                    "别人得知道你看的到底是什么；上面「在看什么」里已经有剧名就接着往下说，"
                    "没有就这会儿定下来。别只来一句「这剧情真离谱」"
                ),
                "effects_per_minute": {"boredom": "-0.004", "curiosity": "-0.0006"},
            },
            "state_slot": "watching",
            "state_label": "在看的剧",
            "visible": False,
            "priority": 4,
            "description": "窝在客厅看会儿剧或节目，看多久由你自己决定；看完常想吐槽两句。",
        },
        {
            "id": "lounge",
            "nickname_text": "瘫着",
            "name": "瘫在沙发上",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["lobby"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 900,
            "duration_max": 3600,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "lounging"},
            "on_complete": {
                "trigger": "none",
                "effects_per_minute": {"affect": "-0.001", "energy": "+0.0006"},
            },
            "visible": False,
            "priority": 3,
            "description": "什么也不干，瘫在沙发上歇一会儿；缓过来了再接着过。",
        },
        # ---- 商业街 ----
        {
            "id": "browse_shop",
            "nickname_text": "逛店中",
            "name": "逛店",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["mall"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 1200,
            "duration_max": 5400,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "shopping"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "说一句刚看到的东西（颜色、手感、价格之类的印象），不要招呼别人来买",
                "effects_per_minute": {"curiosity": "-0.002", "boredom": "-0.003"},
            },
            "visible": False,
            "priority": 4,
            "description": "在商场里逛一圈，逛多久由你自己决定；看到喜欢的会想说两句。",
        },
        {
            "id": "snack_run",
            "nickname_text": "吃东西",
            "name": "吃点小吃",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["snacks"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 1800,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "eating"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "说说刚吃的那份东西什么味道（热的、辣的、太甜了这种），一句就够",
                "effects_per_minute": {
                    "energy": "+0.0012",
                    "valence": "+0.0006",
                    "boredom": "-0.002",
                },
            },
            "visible": False,
            "priority": 4,
            "description": "在小吃街买点东西吃，吃多久由你自己决定；吃完会想说说味道。",
        },
        # ---- 学校 ----
        {
            "id": "attend_class",
            "nickname_text": "听课中",
            "name": "旁听一节课",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["classroom"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 2400,
            "duration_max": 5400,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "attending"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "下课后的一句感想：听懂了什么、哪句让你走神了、或者黑板上的东西挺好看",
                "effects_per_minute": {"curiosity": "-0.0025", "energy": "-0.0008"},
            },
            "visible": False,
            "priority": 5,
            "description": "坐在教室后排听一节课，听多久由你自己决定；下课常想吐槽或分享。",
        },
        {
            "id": "run_laps",
            "nickname_text": "跑步中",
            "name": "跑两圈",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["playground"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 1800,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "running"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "跑完之后喘着说一两句（腿酸、风大、心里痛快），别写成运动报告",
                "effects": {"mood": "mood:畅快"},
                "effects_per_minute": {
                    "energy": "-0.002",
                    "affect": "+0.001",
                    "valence": "+0.0008",
                },
            },
            "visible": False,
            "priority": 4,
            "description": "在操场上跑两圈，跑多久由你自己决定；跑完心情会亮一点。",
        },
        # ---- 公园 ----
        {
            "id": "walk_park",
            "nickname_text": "散步中",
            "name": "散步",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["park_gate", "park_bench", "park_lake"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 900,
            "duration_max": 2700,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "walking_slow"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "说一句路上看到的东西（树、猫、别人在做什么），不用写成游记",
                "effects_per_minute": {
                    "boredom": "-0.004",
                    "valence": "+0.0008",
                    "loneliness": "-0.0006",
                },
            },
            "visible": False,
            "priority": 4,
            "description": "在公园里走一走，走多久由你自己决定；走完心里会松一点。",
        },
        {
            "id": "feed_animals",
            "nickname_text": "喂小动物",
            "name": "喂猫/鸽子",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["park_bench", "park_lake"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 300,
            "duration_max": 1200,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "feeding"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "小声说一句刚才那只小动物什么样、怎么靠近你的；语气软一点",
                "effects_per_minute": {"affect": "+0.0008", "loneliness": "-0.0015"},
            },
            "visible": False,
            "priority": 3,
            "description": "蹲下来喂会儿公园里的猫或者鸽子，喂多久由你自己决定。",
        },
        # ---- 海边 ----
        {
            "id": "sea_breeze",
            "nickname_text": "吹海风",
            "name": "吹海风",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["boardwalk", "beach", "rocks"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 900,
            "duration_max": 3600,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "breezing"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "站在风里的一句感慨（风声、咸味、远处的东西），可以很轻很短",
                "effects_per_minute": {
                    "affect": "-0.0006",
                    "boredom": "-0.003",
                    "loneliness": "+0.0008",
                },
            },
            "visible": False,
            "priority": 4,
            "description": "站在海边吹风，吹多久由你自己决定；风一大容易想很远的事。",
        },
        {
            "id": "paddle",
            "nickname_text": "踩水中",
            "name": "踩水",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["beach"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 1800,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "paddling"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "说一句水有多凉、浪打过来的感觉；可以像小孩一样高兴",
                "effects": {"mood": "mood:雀跃"},
                "effects_per_minute": {"affect": "+0.0012", "valence": "+0.0008"},
            },
            "visible": False,
            "priority": 3,
            "description": "脱了鞋在浅水里踩一会儿，踩多久由你自己决定；踩完会想笑。",
        },
        {
            "id": "collect_shells",
            "nickname_text": "捡贝壳",
            "name": "捡贝壳",
            "category": "continuous",
            "llm_level": "template",
            "scope": "node",
            "allowed_nodes": ["beach", "rocks"],
            "target_type": "none",
            "duration_mode": "llm",
            "duration_min": 600,
            "duration_max": 1800,
            "interruptible": True,
            "preconditions": {},
            "during": {"state": "collecting"},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": "说一句捡到的那个东西什么样（颜色、纹路、像什么），别编数量",
                "effects_per_minute": {"curiosity": "-0.002", "boredom": "-0.002"},
            },
            "visible": False,
            "priority": 3,
            "description": "低头在沙里找好看的贝壳或石头，找多久由你自己决定；捡到的会记在心里。",
        },
        # ---------------- 工具型（需要 AstrBot 里已注册对应工具） ----------------
        {
            "id": "search_web",
            "builtin": True,
            "name": "上网搜索",
            # 瞬时动作：动作一开始就真的去查，拿到结果紧接着用她自己的话讲出来。
            # 做成持续动作的话要等"上网中"结束才调用工具，群里要等好几分钟才看得到结果。
            "category": "instant",
            "llm_level": "tool",
            # 不带默认工具：本机装了哪个搜索工具由用户自己挑，
            # 没选时这一步会被跳过并在日志与编辑器横幅里写明。
            "tool_names": [],
            "tool_fallbacks": [],
            # 检索流水线：多查询 → 结果归一化成证据 →（可选）读正文 → 按证据讲
            "tool_flow": "search",
            "reader_tool_names": [],
            "search_depth": "standard",
            # 查完一次好奇心回落多少：这个值要能把她从阈值（0.7）以上拉下来，
            # 不然冷却一到又去查同一件事（详细说明见 ActionDef.search_satisfy_curiosity）
            "search_satisfy_curiosity": 0.30,
            "scope": "node",
            "allowed_nodes": ["study", "library"],
            "target_type": "none",
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": (
                    "把查到的内容讲给群里听：用你自己的口吻，挑最有用的两三点，别照抄原文、别念网址；"
                    "查到什么说什么，查不到就直说没查到，别拿印象里的东西凑"
                ),
                "effects": {"boredom": "-0.05"},
            },
            "visible": False,
            "priority": 5,
            "description": (
                "上网查东西（在书房的电脑、或者图书馆的公共机位）。"
                "**不知道、拿不准、或者涉及最新消息的事就用它查，"
                "不要凭印象猜、也不要编**：谁、什么时候、哪方面，写进 intent 说清楚就行，"
                "关键词由系统补全。查直播比分、天气、新闻、某个东西现在什么样，都走这个动作。"
            ),
        },
        {
            "id": "check_weather",
            "builtin": True,
            "name": "查天气",
            "category": "instant",
            "llm_level": "tool",
            # 同上：查天气也要用户自己挑一个天气工具
            "tool_names": [],
            "tool_fallbacks": [],
            "scope": "node",
            "allowed_nodes": ["study", "window", "rooftop", "beach"],
            "target_type": "none",
            "interruptible": True,
            "preconditions": {},
            "params": {},
            "on_complete": {
                "trigger": "llm_followup",
                "prompt_hint": (
                    "用两句讲讲天气本身：温度多少、体感怎么样（闷/干/风大）、要不要带伞或加衣、"
                    "适合做点什么。别只感叹一句「好热」「好冷」，也别自己编温度；"
                    "没查到就直说没查到"
                ),
            },
            "visible": False,
            "priority": 4,
            "description": (
                "查今天/现在的天气。有人问天气、或者你想提醒对方带伞加衣时用它；"
                "必须真的查到再说，工具没装或没查到就别猜。"
            ),
        },
    ],
}

DEFAULT_SCHEDULES: dict[str, Any] = {
    "schedules": [
        {
            "id": "morning_greet",
            "enabled": True,
            "time": "08:30",
            "days": ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
            "action_chain": [
                {"type": "walk_to", "target_node": "lobby"},
                {"type": "stretch"},
            ],
            "conditions": {"not_state": ["sleeping"], "min_energy": 0.35},
            "priority": 5,
            "auto_travel": True,
        },
        {
            "id": "dinner_cook",
            "enabled": True,
            "time": "18:00",
            "days": ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
            "action_chain": [
                {"type": "walk_to", "target_node": "kitchen"},
                {"type": "cook"},
            ],
            "conditions": {"not_state": ["sleeping"], "min_energy": 0.3},
            "priority": 6,
            "auto_travel": True,
        },
        {
            "id": "night_sleep",
            "enabled": True,
            "time": "23:30",
            "days": ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
            "action_chain": [
                {"type": "walk_to", "target_node": "bedroom"},
                {"type": "sleep", "duration": 28800},
            ],
            "conditions": {"not_state": ["sleeping"]},
            "priority": 10,
            "auto_travel": True,
        },
    ]
}


def default_world() -> dict[str, Any]:
    """返回默认世界的深拷贝，避免调用方修改常量。"""

    world = copy.deepcopy(DEFAULT_WORLD)
    return world


def default_schedules() -> dict[str, Any]:
    """返回默认日程的深拷贝。"""

    return copy.deepcopy(DEFAULT_SCHEDULES)


def default_actions() -> list[dict[str, Any]]:
    """返回默认动作列表的深拷贝（用来补回被删掉的内置动作）。"""

    return copy.deepcopy(DEFAULT_WORLD.get("actions") or [])


def default_profile() -> dict[str, Any]:
    """返回默认的用户画像配置（关系表 / 亲密度分级 / 开关）的深拷贝。

    老配置里没有这一节时，读入会按这份补上（见 ``parse_world``）。
    """

    return copy.deepcopy(DEFAULT_WORLD.get("profile") or {})
